### ISSUE TITLE
Create script to homogenize repository labels

### ISSUE THREAD

**Issue by gr2m** [octoherd/octoherd#1]
I think the way it could work is

```
$ npx @octoherd/cli \
  --token 0123456789012345678901234567890123456789 \
  --source https://github.com/gr2m/repo-with-the-labels-I-want
  ./script.js \
  "gr2m/*"
```

The script would load the labels from the `source` option, and add them to all my https://github.com/gr2m repositories. If a label with the same name already exists, update the color & description.

I'm not sure about

1. Should existing labels that are not in the `source` repository be deleted?
2. Can labels be deleted if they are being used (I'll check)
3. Would it be useful to add a `--rename` or `--alias` option, to support renaming existing labels?

/cc @bdougie as we discussed this script idea today

**Comment by bdougie** [comment]
Hey checking in on this issue. I generated an `npx create-octoherd-script` new script on stream today and it was a great experience. I am going to work on this example in the next stream.

Homogenizing labels will be useful for some of my GitHub Actions work.

**Comment by zeke** [comment]
> homogenize

Totally stealing this word.

**Comment by gr2m** [comment]
@bdougie did it: https://github.com/octokit/webhooks/pull/436 🎉 

Until I build some kind of website for Octoherd that lists all scripts, you can find all the plugins at https://github.com/topics/octoherd-script?o=desc&s=updated

**Comment by bdougie** [comment]
![](https://media1.giphy.com/media/ae6m4ljnl69urJ539F/giphy.gif)
