### ISSUE TITLE
New vendor compliance documentation

### ISSUE THREAD

**Issue by ahammond** [octoherd/octoherd#42]
In order to use this, our compliance department is asking me the following:

Who is the vendor / contact information (I think I can link them to this repo and the license file)

Where does this run (my understanding is that it's on GH Runners)

**Comment by gr2m** [comment]
> Who is the vendor / contact information (I think I can link them to this repo and the license file)

This is a privately run project. You can contact us by creating an issue here 😄 
@octoherd has a very permissive license: https://github.com/octoherd/octoherd/blob/main/LICENSE.md

> Where does this run (my understanding is that it's on GH Runners)

We do not host any of the scripts, you can run them wherever you want, including GitHub Actions.

**Comment by ahammond** [comment]
And... we got it added. :)
