### ISSUE TITLE
proposal: to enable GitHub Discussions in this repository

### ISSUE THREAD

**Issue by oscard0m** [octoherd/octoherd#5]
I think it would be interesting to open Discussions before materializing them as issues to work on.

**Comment by gr2m** [comment]
My current plan is to replace the scripts in this repository with many separate repositories, one repository per script. And to make it much easier to create a new script with something similar to https://github.com/octokit/create-octokit-project.js/

For discussions, I think we should create an `octoherd/octoherd` repository which we could use as a kind of "landing" page for the whole project.

**Comment by gr2m** [comment]
I've renamed this repository to `octoherd` and enabled discussions
